### ISSUE TITLE
Unable to install package from inside container

### ISSUE THREAD

**Issue by mzico** [GluuFederation/ce-centos#10]
It's not possible to install any package from container. As for example, I went to install 'vim' but it is throwing error: 

 
![yum_error](https://cloud.githubusercontent.com/assets/7156097/8214084/621c4a5e-14ec-11e5-87ad-fb1581d22bb5.png)

**Comment by yurem** [comment]
We fixed this in CE 2.3.0.beta2. Can you try: http://deb-repo.gluu.org/centos/testing/gluu-server-2.3.0.beta2-1.el6.x86_64.rpm ?
