### ISSUE TITLE
Remove perl and prel based check_ssl and install new check_ssl

### ISSUE THREAD

**Issue by yurem** [GluuFederation/ce-centos#3]
We need to install bash based check_ssl instwad of per based version. We need to do:
1) According to yum.log perl has few dependencies. We need to remove perl and depenedent packages:
Jan 28 10:01:58 Installed: perl-Math-Calc-Units-1.07-6.el6.noarch
Jan 28 10:02:16 Installed: perl-Config-Tiny-2.12-7.1.el6.noarch
Jan 28 10:04:06 Installed: perl-YAML-Syck-1.07-4.el6.x86_64
Jan 28 10:04:06 Installed: perl-DBI-1.609-4.el6.x86_64
Jan 28 10:04:06 Installed: fontpackages-filesystem-1.41-1.1.el6.noarch
Jan 28 10:04:06 Installed: dejavu-fonts-common-2.30-2.el6.noarch
Jan 28 10:04:09 Installed: dejavu-lgc-sans-mono-fonts-2.30-2.el6.noarch
Jan 28 10:04:11 Installed: dejavu-sans-mono-fonts-2.30-2.el6.noarch
Jan 28 10:04:11 Installed: rrdtool-1.3.8-7.el6.x86_64
Jan 28 10:04:11 Installed: rrdtool-perl-1.3.8-7.el6.x86_64
Jan 28 10:04:11 Installed: perl-DBD-MySQL-4.013-3.el6.x86_64
Jan 28 10:04:13 Installed: perl-Date-Manip-6.24-1.el6.noarch
Jan 28 10:04:13 Installed: perl-TermReadKey-2.30-13.el6.x86_64
Jan 28 10:04:13 Installed: perl-File-ReadBackwards-1.04-7.el6.noarch
Jan 28 10:04:13 Installed: perl-URI-1.40-2.el6.noarch
Jan 28 10:04:13 Installed: perl-Params-Validate-0.92-3.el6.x86_64
Jan 28 10:04:13 Installed: perl-Class-Accessor-0.31-6.1.el6.noarch

2) Remove old check_ssl
3) Copy check_ssl from ubuntu ce chroot /usr/local/bin to centos_ce
4) Commit changes to gitlab

**Comment by ganesh-at-wiw** [comment]
1. All mentioned packages have been removed.
2. Old check_ssl has been removed
3. check_ssl has been copied.
4. Committed to gitlab.
