### ISSUE TITLE
CE 2.1 CentOS failing 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/ce-centos#7]
Hi guys. This morning I am trying to install the latest version of Gluu CE to test migrating my server settings and users. But I am running into some problems.

First, for the Yum install, I believe there is a typo
wget http://repo.gluu.org/GLUU/Gluu.repo -o /etc/yu.repos.d/Gluu.repo
should be
wget http://repo.gluu.org/GLUU/Gluu.repo -o /etc/yum.repos.d/Gluu.repo

Next, when I try to import the key:
[root@ip-172-31-22-76 ~]# rpm --import /etc/pki/rpm-gpg/Gluu-RPM-GPG-KEY
error: /etc/pki/rpm-gpg/Gluu-RPM-GPG-KEY: key 1 not an armored public key.

And Finally, when I try to install via the rpm:
[root@ip-172-31-22-76 ~]# rpm -ivh http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.src.rpm -vvv
Retrieving http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.src.rpm
D: ============== /var/tmp/rpm-tmp.b05dPi
D: loading keyring from pubkeys in /var/lib/rpm/pubkeys/.key
D: couldn't find any keys in /var/lib/rpm/pubkeys/.key
D: loading keyring from rpmdb
D: opening db environment /var/lib/rpm cdb:mpool:joinenv
D: opening db index /var/lib/rpm/Packages rdonly mode=0x0
D: locked db index /var/lib/rpm/Packages
D: opening db index /var/lib/rpm/Name rdonly mode=0x0
D: read h# 206 Header sanity check: OK
D: added key gpg-pubkey-c105b9de-4e0fd3a3 to keyring
D: read h# 269 Header sanity check: OK
D: added key gpg-pubkey-0608b895-4bd22942 to keyring
D: Using legacy gpg-pubkey(s) from rpmdb
D: Expected size: 634450380 = lead(96)+sigs(180)+pad(4)+data(634450100)
D: Actual size: 634450380
D: /var/tmp/rpm-tmp.b05dPi: Header SHA1 digest: OK (c1802c46d5f9b977a0499af64a742b11656498e5)
D: added source package [0]
D: found 1 source and 0 binary packages
D: Expected size: 634450380 = lead(96)+sigs(180)+pad(4)+data(634450100)
D: Actual size: 634450380
D: InstallSourcePackage at: psm.c:244: Header SHA1 digest: OK (c1802c46d5f9b977a0499af64a742b11656498e5)
1:gluu-server D: ========== Directories not explicitly included in package:
D: 0 /root/rpmbuild/SPECS/
D: 1 /root/rpmbuild/SOURCES/
D: ==========
D: fini 100644 1 ( 0, 0) 3645 /root/rpmbuild/SPECS/gluu-CE.spec;551eb85e unknown
D: fini 100755 1 ( 0, 0) 7344 /root/rpmbuild/SOURCES/gluu-server;551eb85e unknown

##################################### [100%]

D: fini 100644 1 ( 0, 0) 646898124 /root/rpmbuild/SOURCES/gluu-server.tar.gz;551eb85e unknown
D: fini 100644 1 ( 0, 0) 2821 /root/rpmbuild/SOURCES/profile;551eb85e unknown
GZDIO: 78969 reads, 646912564 total bytes in 15.820822 secs
D: closed db index /var/lib/rpm/Name
D: closed db index /var/lib/rpm/Packages
D: closed db environment /var/lib/rpm
[root@ip-172-31-22-76 ~]# service gluu-server start
gluu-server: unrecognized service
[root@ip-172-31-22-76 ~]# cat /etc/redhat-release
CentOS release 6.5 (Final)

The link to the ticket: https://support.gluu.org/view/installation/installation-problems-centos-ce-21/1769

**Comment by prabhu-rajendran-payoda** [comment]
I face this same issue in CentOS 6.5(Final)

$ rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU
error: /etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU: key 1 not an armored public key.

**Comment by prabhu-rajendran-payoda** [comment]
On trying 

$ rpm -ivh http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.src.rpm -vvv

Retrieving http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.src.rpm
D: ============== /var/tmp/rpm-tmp.qlVsEN
D: loading keyring from pubkeys in /var/lib/rpm/pubkeys/*.key
D: couldn't find any keys in /var/lib/rpm/pubkeys/*.key
D: loading keyring from rpmdb
D: opening  db environment /var/lib/rpm cdb:mpool:joinenv
D: opening  db index       /var/lib/rpm/Packages rdonly mode=0x0
D: locked   db index       /var/lib/rpm/Packages
D: opening  db index       /var/lib/rpm/Name rdonly mode=0x0
D:  read h#    1272 Header sanity check: OK
D: added key gpg-pubkey-6b8d79e6-3f49313d to keyring
D:  read h#    1273 Header sanity check: OK
D: added key gpg-pubkey-c105b9de-4e0fd3a3 to keyring
D:  read h#    1321 Header sanity check: OK
D: added key gpg-pubkey-d50582e6-4a3feef6 to keyring
D:  read h#    1400 Header sanity check: OK
D: added key gpg-pubkey-79ea5ed4-508d25a6 to keyring
D:  read h#    1857 Header sanity check: OK
D: added key gpg-pubkey-0608b895-4bd22942 to keyring
D: Using legacy gpg-pubkey(s) from rpmdb
D: adding 165 args from manifest.
D: ============== <!DOCTYPE
error: open of <!DOCTYPE failed: No such file or directory
D: ============== html
error: open of html failed: No such file or directory
D: ============== PUBLIC
error: open of PUBLIC failed: No such file or directory
D: ============== -//W3C//DTD HTML 4.01//EN>
error: open of -//W3C//DTD HTML 4.01//EN> failed: No such file or directory
D: ============== <html>
error: open of <html> failed: No such file or directory
D: ============== <head>
error: open of <head> failed: No such file or directory
D: ============== <meta
error: open of <meta failed: No such file or directory
D: ============== http-equiv=Content-Type
error: open of http-equiv=Content-Type failed: No such file or directory
D: ============== content=text/html; charset=UTF-8>
error: open of content=text/html; charset=UTF-8> failed: No such file or directory
D: ============== <style
error: open of <style failed: No such file or directory
D: ============== type=text/css>
error: open of type=text/css> failed: No such file or directory
D: ============== html,body{
error: open of html,body{ failed: No such file or directory
D: ============== height:100%;
error: open of height:100%; failed: No such file or directory
D: ============== padding:0;
error: open of padding:0; failed: No such file or directory
D: ============== margin:0;
error: open of margin:0; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== .oc{
error: open of .oc{ failed: No such file or directory
D: ============== display:table;
error: open of display:table; failed: No such file or directory
D: ============== width:100%;
error: open of width:100%; failed: No such file or directory
D: ============== height:100%;
error: open of height:100%; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== .ic{
error: open of .ic{ failed: No such file or directory
D: ============== display:table-cell;
error: open of display:table-cell; failed: No such file or directory
D: ============== vertical-align:middle;
error: open of vertical-align:middle; failed: No such file or directory
D: ============== height:100%;
error: open of height:100%; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== form{
error: open of form{ failed: No such file or directory
D: ============== display:block;
error: open of display:block; failed: No such file or directory
D: ============== background:
error: open of background: failed: No such file or directory
D: ============== border:2px
error: open of border:2px failed: No such file or directory
D: ============== solid
error: open of solid failed: No such file or directory
D: ============== green;
error: open of green; failed: No such file or directory
D: ============== padding:0
error: open of padding:0 failed: No such file or directory
D: ============== 0
error: open of 0 failed: No such file or directory
D: ============== 25px
error: open of 25px failed: No such file or directory
D: ============== 0;
error: open of 0; failed: No such file or directory
D: ============== width:600px;
error: open of width:600px; failed: No such file or directory
D: ============== font-family:helvetica,sans-serif;
error: open of font-family:helvetica,sans-serif; failed: No such file or directory
D: ============== font-size:20px;
error: open of font-size:20px; failed: No such file or directory
D: ============== margin:15px
error: open of margin:15px failed: No such file or directory
D: ============== auto;
error: open of auto; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== .fel,.fer,.fec{
error: open of .fel,.fer,.fec{ failed: No such file or directory
D: ============== text-align:center;
error: open of text-align:center; failed: No such file or directory
D: ============== width:350px;
error: open of width:350px; failed: No such file or directory
D: ============== margin:0
error: open of margin:0 failed: No such file or directory
D: ============== auto;
error: open of auto; failed: No such file or directory
D: ============== padding:10px;
error: open of padding:10px; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== .fel{
error: open of .fel{ failed: No such file or directory
D: ============== text-align:left;
error: open of text-align:left; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== .fer{
error: open of .fer{ failed: No such file or directory
D: ============== text-align:right;
error: open of text-align:right; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== h1{
error: open of h1{ failed: No such file or directory
D: ============== font-weight:bold;
error: open of font-weight:bold; failed: No such file or directory
D: ============== font-size:21px;
error: open of font-size:21px; failed: No such file or directory
D: ============== margin:0;
error: open of margin:0; failed: No such file or directory
D: ============== padding:20px
error: open of padding:20px failed: No such file or directory
D: ============== 10px;
error: open of 10px; failed: No such file or directory
D: ============== text-align:center;
error: open of text-align:center; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== p{
error: open of p{ failed: No such file or directory
D: ============== margin:15px
error: open of margin:15px failed: No such file or directory
D: ============== auto;
error: open of auto; failed: No such file or directory
D: ============== width:75%;
error: open of width:75%; failed: No such file or directory
D: ============== text-align:left;
error: open of text-align:left; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== ul{
error: open of ul{ failed: No such file or directory
D: ============== margin:15px
error: open of margin:15px failed: No such file or directory
D: ============== auto;
error: open of auto; failed: No such file or directory
D: ============== width:75%;
error: open of width:75%; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== h2{
error: open of h2{ failed: No such file or directory
D: ============== margin:25px
error: open of margin:25px failed: No such file or directory
D: ============== 10px;
error: open of 10px; failed: No such file or directory
D: ============== font-weight:bold;
error: open of font-weight:bold; failed: No such file or directory
D: ============== text-align:center;
error: open of text-align:center; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== label,h2{
error: open of label,h2{ failed: No such file or directory
D: ============== font-size:16px;
error: open of font-size:16px; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== .logo{
error: open of .logo{ failed: No such file or directory
D: ============== background:
error: open of background: failed: No such file or directory
D: ============== padding-top:80px;
error: open of padding-top:80px; failed: No such file or directory
D: ============== }
error: open of } failed: No such file or directory
D: ============== </style>
error: open of </style> failed: No such file or directory
D: ============== <title>
error: open of <title> failed: No such file or directory
D: ============== Gateway
error: open of Gateway failed: No such file or directory
D: ============== Authentication
error: open of Authentication failed: No such file or directory
D: ============== </title>
error: open of </title> failed: No such file or directory
D: ============== </head>
error: open of </head> failed: No such file or directory
D: ============== <body>
error: open of <body> failed: No such file or directory
D: ============== <div
error: open of <div failed: No such file or directory
D: ============== class=oc>
error: open of class=oc> failed: No such file or directory
D: ============== <div
error: open of <div failed: No such file or directory
D: ============== class=ic>
error: open of class=ic> failed: No such file or directory
D: ============== <form
error: open of <form failed: No such file or directory
D: ============== action=/
error: open of action=/ failed: No such file or directory
D: ============== method=post>
error: open of method=post> failed: No such file or directory
D: ============== <input
error: open of <input failed: No such file or directory
D: ============== type=hidden
error: open of type=hidden failed: No such file or directory
D: ============== name=4Tredir
error: open of name=4Tredir failed: No such file or directory
D: ============== value=http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.src.rpm>
error: open of value=http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.src.rpm> failed: No such file or directory
D: ============== <input
error: open of <input failed: No such file or directory
D: ============== type=hidden
error: open of type=hidden failed: No such file or directory
D: ============== name=magic
error: open of name=magic failed: No such file or directory
D: ============== value=020103cd5eebe52f>
error: open of value=020103cd5eebe52f> failed: No such file or directory
D: ============== <h1
error: open of <h1 failed: No such file or directory
D: ============== class=logo>
error: open of class=logo> failed: No such file or directory
D: ============== Internet
error: open of Internet failed: No such file or directory
D: ============== Acces
error: open of Acces failed: No such file or directory
D: ============== Authentication
error: open of Authentication failed: No such file or directory
D: ============== Required
error: open of Required failed: No such file or directory
D: ============== </h1>
error: open of </h1> failed: No such file or directory
D: ============== <h2>
error: open of <h2> failed: No such file or directory
D: ============== Please
error: open of Please failed: No such file or directory
D: ============== enter
error: open of enter failed: No such file or directory
D: ============== your
error: open of your failed: No such file or directory
D: ============== username
error: open of username failed: No such file or directory
D: ============== and
error: open of and failed: No such file or directory
D: ============== password
error: open of password failed: No such file or directory
D: ============== to
error: open of to failed: No such file or directory
D: ============== continue.
error: open of continue. failed: No such file or directory
D: ============== </h2>
error: open of </h2> failed: No such file or directory
D: ============== <div
error: open of <div failed: No such file or directory
D: ============== class=fel>
error: open of class=fel> failed: No such file or directory
D: ============== <label
error: open of <label failed: No such file or directory
D: ============== for=ft_un>
error: open of for=ft_un> failed: No such file or directory
D: ============== Username:
error: open of Username: failed: No such file or directory
D: ============== </label>
error: open of </label> failed: No such file or directory
D: ============== <input
error: open of <input failed: No such file or directory
D: ============== name=username
error: open of name=username failed: No such file or directory
D: ============== id=ft_un
error: open of id=ft_un failed: No such file or directory
D: ============== type=text
error: open of type=text failed: No such file or directory
D: ============== autocorrect=off
error: open of autocorrect=off failed: No such file or directory
D: ============== autocapitalize=off
error: open of autocapitalize=off failed: No such file or directory
D: ============== style=width:230px>
error: open of style=width:230px> failed: No such file or directory
D: ============== <br>
error: open of <br> failed: No such file or directory
D: ============== </div>
error: open of </div> failed: No such file or directory
D: ============== <div
error: open of <div failed: No such file or directory
D: ============== class=fel>
error: open of class=fel> failed: No such file or directory
D: ============== <label
error: open of <label failed: No such file or directory
D: ============== for=ft_pd>
error: open of for=ft_pd> failed: No such file or directory
D: ============== Password:
error: open of Password: failed: No such file or directory
D: ============== </label>
error: open of </label> failed: No such file or directory
D: ============== <input
error: open of <input failed: No such file or directory
D: ============== name=password
error: open of name=password failed: No such file or directory
D: ============== id=ft_pd
error: open of id=ft_pd failed: No such file or directory
D: ============== type=password
error: open of type=password failed: No such file or directory
D: ============== autocomplete=off
error: open of autocomplete=off failed: No such file or directory
D: ============== style=width:230px>
error: open of style=width:230px> failed: No such file or directory
D: ============== </div>
error: open of </div> failed: No such file or directory
D: ============== <div
error: open of <div failed: No such file or directory
D: ============== class=fer>
error: open of class=fer> failed: No such file or directory
D: ============== <input
error: open of <input failed: No such file or directory
D: ============== type=submit
error: open of type=submit failed: No such file or directory
D: ============== value=
error: open of value= failed: No such file or directory
D: ============== Continue>
error: open of Continue> failed: No such file or directory
D: ============== </div>
error: open of </div> failed: No such file or directory
D: ============== </form>
error: open of </form> failed: No such file or directory
D: ============== </div>
error: open of </div> failed: No such file or directory
D: ============== </body>
error: open of </body> failed: No such file or directory
D: ============== </html>
error: open of </html> failed: No such file or directory
D: found 0 source and 0 binary packages
D: closed   db index       /var/lib/rpm/Name
D: closed   db index       /var/lib/rpm/Packages
D: closed   db environment /var/lib/rpm

**Comment by adrian-gluu** [comment]
Hello prabhu,

why are you trying to install our src.rpm instead of .rpm? any particular reason? I will recommend you to try our .rpm if you want to install our gluu-server you will need binarys instead of source files.

Cheers, Adrian.-

**Comment by prabhu-rajendran-payoda** [comment]
Hello Adrian,

I installed gluu-server without any hurdles in CentOS 6.5.. The above issue was due to Firewall block..

Now I could not able to get gluu in web browser..  https://{hostname}  does not work..!

**Comment by prabhu-rajendran-payoda** [comment]
Finally, I could able to get the login page...

Once I tried to login using credentials, as provided in wiki, I failed..

**Comment by mzico** [comment]
@prabhu-rajendran-payoda : Use the password which you provided during installation for user 'admin'. 
If you fail, check /opt/tomcat/logs/oxauth.log for the reason.

**Comment by prabhu-rajendran-payoda** [comment]
Yes, able to login.. But failed to login using new registered user...

**Comment by mzico** [comment]
Same... check /opt/tomcat/logs/oxauth.log for the reason.

**Comment by prabhu-rajendran-payoda** [comment]
I found it.. Logged-in.. Thanks
