### ISSUE TITLE
CE 2.1 CentOS installation problem

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/ce-centos#8]
Hello, I have tried to install the CE 2.1 in CentOS using the installation instruction in the following link.
http://www.gluu.org/docs/admin-guide/installation/centos/
I run into some problem and when I try to to start the gluu-server using the __# service gluu-server start__ it tells me **"gluu-server: unrecognized service"**. 
Please see the following screenshots.
![centos intallation](https://cloud.githubusercontent.com/assets/7703245/7049601/8b899aae-de3c-11e4-905d-843176b1b03a.png)
![installation problem](https://cloud.githubusercontent.com/assets/7703245/7049603/92a20704-de3c-11e4-818e-41a628c7484e.png)

**Comment by adrian-gluu** [comment]
can you try to install the rpm avoiding yum
first of all
remove with yum glue-server pkg
and follow the instructions avoiding yum just use rpm -Uvh http://...
can u try that?
[zamil first of all "yum remove gluu-server"

and then can you try this way:
rpm -ivh http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.src.rpm

 after that: 
service gluu-server start

**Comment by zamilskhan** [comment]
I get this error when I run the "service gluu-server start" command. I installed it with "yum install --nogpgcheck gluu-server" command.
ERROR: Cant start gluu server.
HINT: Please manually remove /var/run/gluu-server.pid and unmount chroot container by running
rm -f /var/run/gluu-server.pid
df -aP | grep gluu-server | awk '{print $6}' | xargs -I {} umount -l {}

**Comment by adrian-gluu** [comment]
[root@repoadrian ~]# rpm -ivh http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.x86_64.rpm
Retrieving http://repo.gluu.org/GLUU/centos/6.5/base/x86_64/Packages/gluu-server-2.1.0-0.el6.x86_64.rpm
Preparing...                ########################################### [100%]
   1:gluu-server            ########################################### [100%]
[root@repoadrian ~]#  service gluu-server start
Starting Gluu server, please wait...

[root@repoadrian ~]# service gluu-server status
gluu-server is running: started
[root@repoadrian ~]#
[root@repoadrian ~]# yum remove^C
[root@repoadrian ~]# man yum
[root@repoadrian ~]# service gluu-server status^C
[root@repoadrian ~]# yum remove gluu-server
Loaded plugins: fastestmirror
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package gluu-server.x86_64 0:2.1.0-0.el6 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================
 Package                      Arch                    Version                      Repository                  Size
====================================================================================================================
Removing:
 gluu-server                  x86_64                  2.1.0-0.el6                  installed                  1.4 G

Transaction Summary
====================================================================================================================
Remove        1 Package(s)

Installed size: 1.4 G
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.
  Erasing    : gluu-server-2.1.0-0.el6.x86_64                                                                   1/1
Checking to make sure Gluu Server is down...
  Verifying  : gluu-server-2.1.0-0.el6.x86_64                                                                   1/1

Removed:
  gluu-server.x86_64 0:2.1.0-0.el6

Complete!
[root@repoadrian ~]# wget http://repo.gluu.org/GLUU/Gluu.repo -O /etc/yum.repos.d/Gluu.repo
--2015-04-08 13:55:27--  http://repo.gluu.org/GLUU/Gluu.repo
Resolving repo.gluu.org... 45.55.175.222
Connecting to repo.gluu.org|45.55.175.222|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 167 [text/plain]
Saving to: “/etc/yum.repos.d/Gluu.repo”

100%[==========================================================================>] 167         --.-K/s   in 0s

2015-04-08 13:55:27 (15.3 MB/s) - “/etc/yum.repos.d/Gluu.repo” saved [167/167]

[root@repoadrian ~]# wget http://repo.gluu.org/GLUU/RPM-GPG-KEY-GLUU -O /etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU
--2015-04-08 13:55:33--  http://repo.gluu.org/GLUU/RPM-GPG-KEY-GLUU
Resolving repo.gluu.org... 45.55.175.222
Connecting to repo.gluu.org|45.55.175.222|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3133 (3.1K) [text/plain]
Saving to: “/etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU”

100%[==========================================================================>] 3,133       --.-K/s   in 0s

2015-04-08 13:55:33 (155 MB/s) - “/etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU” saved [3133/3133]

[root@repoadrian ~]# rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-GLUU
[root@repoadrian ~]# yum clean all
Loaded plugins: fastestmirror
Cleaning repos: Gluu-rpm-repo base extras updates
Cleaning up Everything
Cleaning up list of fastest mirrors
[root@repoadrian ~]# yum install --nogpgcheck gluu-server
Loaded plugins: fastestmirror
Setting up Install Process
Determining fastest mirrors
 * base: mirrors.lga7.us.voxel.net
 * extras: mirrors.lga7.us.voxel.net
 * updates: mirrors.lga7.us.voxel.net
Gluu-rpm-repo                                                                                | 2.9 kB     00:00
Gluu-rpm-repo/primary_db                                                                     |  98 kB     00:00
base                                                                                         | 3.7 kB     00:00
base/primary_db                                                                              | 4.6 MB     00:00
extras                                                                                       | 3.4 kB     00:00
extras/primary_db                                                                            |  30 kB     00:00
updates                                                                                      | 3.4 kB     00:00
updates/primary_db                                                                           | 2.7 MB     00:00
Resolving Dependencies
--> Running transaction check
---> Package gluu-server.x86_64 0:2.1.0-0.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================
 Package                     Arch                   Version                     Repository                     Size
====================================================================================================================
Installing:
 gluu-server                 x86_64                 2.1.0-0.el6                 Gluu-rpm-repo                 614 M

Transaction Summary
====================================================================================================================
Install       1 Package(s)

Total download size: 614 M
Installed size: 1.4 G
Is this ok [y/N]: y
Downloading Packages:
gluu-server-2.1.0-0.el6.x86_64.rpm                                                           | 614 MB     00:14
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : gluu-server-2.1.0-0.el6.x86_64                                                                   1/1
  Verifying  : gluu-server-2.1.0-0.el6.x86_64                                                                   1/1

Installed:
  gluu-server.x86_64 0:2.1.0-0.el6

Complete!
[root@repoadrian ~]# service gluu-server status
gluu-server is not running
[root@repoadrian ~]# service gluu-server start
Starting Gluu server, please wait...

[root@repoadrian ~]# service gluu-server status
gluu-server is running: started
[root@repoadrian ~]#

Everything is fine there now just fixed our centos installation guide with "--nogpgcheck"
